"""add unique constraint wallet user address chain

Revision ID: 4fe02299585f
Revises: c49d498c561f
Create Date: 2026-01-29 08:21:25.462366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe02299585f'
down_revision: Union[str, Sequence[str], None] = 'c49d498c561f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_wallet_user_address_chain', 'wallet', ['user_id', 'address', 'chain'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wallet_user_address_chain', 'wallet', type_='unique')
    # ### end Alembic commands ###
